//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System_For_Fitness_Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachingSchedule
    {
        public System.Guid Shedule_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public Nullable<System.DateTime> CoachingDate { get; set; }
        public Nullable<System.TimeSpan> CoachingStart { get; set; }
        public Nullable<System.TimeSpan> CoachingEnd { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
