//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System_For_Fitness_Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public System.Guid Expense_ID { get; set; }
        public Nullable<int> ExpenseType_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> ExpenseCost { get; set; }
    
        public virtual ExpensesType ExpensesType { get; set; }
    }
}
