//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System_For_Fitness_Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid User_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Password { get; set; }
        public Nullable<int> Access_ID { get; set; }
    
        public virtual AccessType AccessType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
